// GENERATED — do not edit by hand.
// Regenerate after adding or replacing demo frames in public/demos/.
//
// Source: free-exercise-db (https://github.com/yuhonas/free-exercise-db), images
// by Everkinetic (https://github.com/everkinetic/data), licensed CC BY-SA 4.0
// (https://creativecommons.org/licenses/by-sa/4.0/). Frames were centre-cropped
// to square and resized to 480px; those adaptations remain CC BY-SA 4.0.

/** Exercises with a two-frame photo demo: `<id>-0.jpg` and `<id>-1.jpg`. */
export const FRAME_DEMOS = new Set<string>([
  'air-bike',
  'band-row',
  'bench-dip',
  'butt-kicks',
  'bw-squat',
  'calf-raise',
  'calf-stretch',
  'cat-cow',
  'chin-up',
  'dead-bug',
  'diamond-push-up',
  'dumbbell-bicep-curl',
  'dumbbell-flyes',
  'dumbbell-rear-lunge',
  'dumbbell-row',
  'dumbbell-shrug',
  'dumbbell-squat',
  'figure-4-stretch',
  'freehand-jump-squat',
  'glute-bridge',
  'glute-kickback',
  'hamstring-stretch',
  'handstand-push-up',
  'hip-circles',
  'hip-flexor-stretch',
  'hyperextension',
  'incline-push-up',
  'inverted-row',
  'lying-leg-raise',
  'mountain-climber',
  'negative-pull-up',
  'overhead-press',
  'plank',
  'plyo-push-up',
  'pull-up',
  'push-up',
  'push-up-to-side-plank',
  'reverse-crunch',
  'russian-twist',
  'scapular-pull-up',
  'side-plank',
  'single-leg-glute-bridge',
  'sit-up',
  'split-squat',
  'step-up-knee-raise',
  'stiff-legged-deadlift',
  'triceps-dip',
  'walking-lunge',
  'worlds-greatest-stretch',
])

/** Source exercise name each demo was taken from, for the credits screen. */
export const DEMO_CREDITS: Record<string, string> = {
  'air-bike': "Air Bike",
  'band-row': "Seated Cable Rows",
  'bench-dip': "Bench Dips",
  'butt-kicks': "Double Leg Butt Kick",
  'bw-squat': "Bodyweight Squat",
  'calf-raise': "Standing Dumbbell Calf Raise",
  'calf-stretch': "Standing Gastrocnemius Calf Stretch",
  'cat-cow': "Cat Stretch",
  'chin-up': "Chin-Up",
  'dead-bug': "Dead Bug",
  'diamond-push-up': "Close-Grip Push-Up off of a Dumbbell",
  'dumbbell-bicep-curl': "Dumbbell Bicep Curl",
  'dumbbell-flyes': "Dumbbell Flyes",
  'dumbbell-rear-lunge': "Dumbbell Rear Lunge",
  'dumbbell-row': "One-Arm Dumbbell Row",
  'dumbbell-shrug': "Dumbbell Shrug",
  'dumbbell-squat': "Dumbbell Squat",
  'figure-4-stretch': "IT Band and Glute Stretch",
  'freehand-jump-squat': "Freehand Jump Squat",
  'glute-bridge': "Butt Lift (Bridge)",
  'glute-kickback': "Glute Kickback",
  'hamstring-stretch': "Standing Hamstring and Calf Stretch",
  'handstand-push-up': "Handstand Push-Ups",
  'hip-circles': "Standing Hip Circles",
  'hip-flexor-stretch': "Kneeling Hip Flexor",
  'hyperextension': "Hyperextensions With No Hyperextension Bench",
  'incline-push-up': "Incline Push-Up",
  'inverted-row': "Inverted Row",
  'lying-leg-raise': "Flat Bench Lying Leg Raise",
  'mountain-climber': "Mountain Climbers",
  'negative-pull-up': "Band Assisted Pull-Up",
  'overhead-press': "Dumbbell Shoulder Press",
  'plank': "Plank",
  'plyo-push-up': "Plyo Push-up",
  'pull-up': "Pullups",
  'push-up': "Pushups",
  'push-up-to-side-plank': "Push Up to Side Plank",
  'reverse-crunch': "Reverse Crunch",
  'russian-twist': "Russian Twist",
  'scapular-pull-up': "Scapular Pull-Up",
  'side-plank': "Side Bridge",
  'single-leg-glute-bridge': "Single Leg Glute Bridge",
  'sit-up': "Sit-Up",
  'split-squat': "Split Squats",
  'step-up-knee-raise': "Step-up with Knee Raise",
  'stiff-legged-deadlift': "Stiff-Legged Dumbbell Deadlift",
  'triceps-dip': "Dips - Triceps Version",
  'walking-lunge': "Bodyweight Walking Lunge",
  'worlds-greatest-stretch': "World's Greatest Stretch",
}
