import type { StrengthExercise } from './types'

// v1 seed library — 24 exercises (spec §5). Bodyweight-first: every category is
// performable with equipment: ['none']. Bundled as a constant (not seeded into
// Dexie). estSecondsPerSet includes the working set only; rest is added by the
// duration math in resolve.ts.

export const STRENGTH_LIBRARY: StrengthExercise[] = [
  // ---- Legs (6) ----
  {
    id: 'bw-squat',
    name: 'Bodyweight Squat',
    category: 'legs',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    regressionOf: 'split-squat',
    instructionSteps: [
      'Stand feet shoulder-width, toes slightly out.',
      'Sit hips back and down, chest tall.',
      'Drive through mid-foot to stand.',
    ],
    commonMistakes: ['Knees caving inward', 'Heels lifting off the floor'],
    defaultSets: 3,
    defaultReps: '12–15',
    restSeconds: 45,
    estSecondsPerSet: 40,
    runInterference: 'high',
  },
  {
    id: 'split-squat',
    name: 'Split Squat',
    category: 'legs',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['none', 'dumbbells'],
    difficulty: 'intermediate',
    progressionOf: 'bw-squat',
    regressionOf: 'bulgarian-split-squat',
    instructionSteps: [
      'Stagger stance, one long stride apart.',
      'Lower back knee toward the floor.',
      'Push through front heel to rise.',
    ],
    commonMistakes: ['Front knee drifting past toes', 'Leaning too far forward'],
    defaultSets: 3,
    defaultReps: '10 / leg',
    restSeconds: 60,
    estSecondsPerSet: 50,
    runInterference: 'high',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'legs',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['none', 'dumbbells'],
    difficulty: 'advanced',
    progressionOf: 'split-squat',
    instructionSteps: [
      'Rest rear foot on a chair or bench.',
      'Lower straight down over the front foot.',
      'Keep front shin near vertical.',
    ],
    commonMistakes: ['Bouncing at the bottom', 'Weight shifting onto back foot'],
    defaultSets: 3,
    defaultReps: '8 / leg',
    restSeconds: 60,
    estSecondsPerSet: 55,
    runInterference: 'high',
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'legs',
    primaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['none'],
    difficulty: 'beginner',
    regressionOf: 'single-leg-glute-bridge',
    instructionSteps: [
      'Lie on back, knees bent, feet flat.',
      'Squeeze glutes and lift hips to a line.',
      'Pause at the top, lower with control.',
    ],
    commonMistakes: ['Arching the lower back', 'Pushing through the toes'],
    defaultSets: 3,
    defaultReps: '15',
    restSeconds: 40,
    estSecondsPerSet: 35,
    runInterference: 'medium',
  },
  {
    id: 'single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    category: 'legs',
    primaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['none'],
    difficulty: 'intermediate',
    progressionOf: 'glute-bridge',
    instructionSteps: [
      'Bridge position, extend one leg straight.',
      'Lift hips using the planted leg only.',
      'Keep hips level throughout.',
    ],
    commonMistakes: ['Hips tilting to one side', 'Using momentum to swing up'],
    defaultSets: 3,
    defaultReps: '10 / leg',
    restSeconds: 45,
    estSecondsPerSet: 45,
    runInterference: 'medium',
  },
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    category: 'legs',
    primaryMuscles: ['calves'],
    equipment: ['none', 'dumbbells'],
    difficulty: 'beginner',
    instructionSteps: [
      'Stand tall, balls of feet on an edge.',
      'Rise onto toes as high as possible.',
      'Lower slowly below the step.',
    ],
    commonMistakes: ['Rushing the reps', 'Not using full range of motion'],
    defaultSets: 3,
    defaultReps: '20',
    restSeconds: 40,
    estSecondsPerSet: 35,
    runInterference: 'medium',
  },

  // ---- Core (6) ----
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    category: 'core',
    primaryMuscles: ['deep core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Lie on back, arms up, knees over hips.',
      'Lower opposite arm and leg slowly.',
      'Keep lower back pressed to the floor.',
    ],
    commonMistakes: ['Back arching off the floor', 'Holding your breath'],
    defaultSets: 3,
    defaultReps: '10 / side',
    restSeconds: 30,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    primaryMuscles: ['core', 'shoulders'],
    equipment: ['none'],
    difficulty: 'beginner',
    regressionOf: 'side-plank',
    instructionSteps: [
      'Forearms under shoulders, body in a line.',
      'Brace abs and squeeze glutes.',
      'Hold steady, breathe normally.',
    ],
    commonMistakes: ['Hips sagging or piking up', 'Dropping the head'],
    defaultSets: 3,
    defaultReps: '45s hold',
    restSeconds: 40,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'core',
    primaryMuscles: ['obliques'],
    equipment: ['none'],
    difficulty: 'intermediate',
    progressionOf: 'plank',
    instructionSteps: [
      'Forearm under shoulder, stack the feet.',
      'Lift hips into a straight side line.',
      'Hold tall, then switch sides.',
    ],
    commonMistakes: ['Hips sinking toward the floor', 'Rotating the chest down'],
    defaultSets: 2,
    defaultReps: '30s / side',
    restSeconds: 40,
    estSecondsPerSet: 60,
    runInterference: 'low',
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    category: 'core',
    primaryMuscles: ['core', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'On all fours, wrists under shoulders.',
      'Extend opposite arm and leg level.',
      'Pause, return, keep hips square.',
    ],
    commonMistakes: ['Twisting the torso', 'Overarching the lower back'],
    defaultSets: 3,
    defaultReps: '10 / side',
    restSeconds: 30,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Hold',
    category: 'core',
    primaryMuscles: ['core'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Lie on back, arms overhead, legs straight.',
      'Lift shoulders and legs off the floor.',
      'Press lower back down, hold the dish.',
    ],
    commonMistakes: ['Lower back lifting off the floor', 'Raising legs too high'],
    defaultSets: 3,
    defaultReps: '30s hold',
    restSeconds: 40,
    estSecondsPerSet: 35,
    runInterference: 'low',
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    category: 'core',
    primaryMuscles: ['core', 'hip flexors'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Start in a strong push-up position.',
      'Drive knees toward chest, alternating fast.',
      'Keep hips low and shoulders stacked.',
    ],
    commonMistakes: ['Hips bouncing high', 'Hands drifting forward'],
    defaultSets: 3,
    defaultReps: '30s',
    restSeconds: 30,
    estSecondsPerSet: 35,
    runInterference: 'medium',
  },

  // ---- Push (5) ----
  {
    id: 'incline-push-up',
    name: 'Incline / Knee Push-Up',
    category: 'push',
    primaryMuscles: ['chest', 'triceps'],
    equipment: ['none'],
    difficulty: 'beginner',
    regressionOf: 'push-up',
    instructionSteps: [
      'Hands on a raised surface or knees down.',
      'Lower chest with elbows about 45°.',
      'Press back up, body in a line.',
    ],
    commonMistakes: ['Flaring elbows wide', 'Hips leading the movement'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 45,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'push',
    primaryMuscles: ['chest', 'triceps', 'shoulders'],
    equipment: ['none'],
    difficulty: 'intermediate',
    progressionOf: 'incline-push-up',
    regressionOf: 'diamond-push-up',
    instructionSteps: [
      'Hands under shoulders, body braced straight.',
      'Lower until chest nearly touches floor.',
      'Press up fully, elbows tucked ~45°.',
    ],
    commonMistakes: ['Sagging hips', 'Partial range of motion'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 60,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'diamond-push-up',
    name: 'Diamond Push-Up',
    category: 'push',
    primaryMuscles: ['triceps', 'chest'],
    equipment: ['none'],
    difficulty: 'advanced',
    progressionOf: 'push-up',
    instructionSteps: [
      'Form a diamond with your hands.',
      'Lower chest toward the hands.',
      'Keep elbows tight to the body.',
    ],
    commonMistakes: ['Elbows flaring outward', 'Hips rising first'],
    defaultSets: 3,
    defaultReps: '8–10',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-Up',
    category: 'push',
    primaryMuscles: ['shoulders', 'triceps'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Hips high in an inverted-V shape.',
      'Lower the crown of your head down.',
      'Press back up over the hands.',
    ],
    commonMistakes: ['Letting hips drop mid-rep', 'Hands too far forward'],
    defaultSets: 3,
    defaultReps: '8–10',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'push',
    primaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbells', 'gym'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Dumbbells at shoulders, elbows under wrists.',
      'Brace core, press straight overhead.',
      'Lower under control to the shoulders.',
    ],
    commonMistakes: ['Arching the lower back', 'Pressing the weights forward'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },

  // ---- Pull (4) ----
  {
    id: 'band-row',
    name: 'Band / Towel Row',
    category: 'pull',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['none', 'resistanceBand'],
    difficulty: 'beginner',
    regressionOf: 'dumbbell-row',
    instructionSteps: [
      'Anchor a band (or towel around a post).',
      'Row elbows back, squeezing shoulder blades.',
      'Return slowly, keeping chest tall.',
    ],
    commonMistakes: ['Shrugging the shoulders', 'Using momentum to yank'],
    defaultSets: 3,
    defaultReps: '12–15',
    restSeconds: 45,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    category: 'pull',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['dumbbells', 'gym'],
    difficulty: 'intermediate',
    progressionOf: 'band-row',
    instructionSteps: [
      'Hinge at hips, flat back, one hand supported.',
      'Row the dumbbell to your hip.',
      'Lower fully, feeling the lat stretch.',
    ],
    commonMistakes: ['Rounding the back', 'Twisting the torso to lift'],
    defaultSets: 3,
    defaultReps: '10 / side',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'negative-pull-up',
    name: 'Negative Pull-Up',
    category: 'pull',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['pullUpBar', 'gym'],
    difficulty: 'intermediate',
    regressionOf: 'pull-up',
    instructionSteps: [
      'Jump or step to the top position.',
      'Lower yourself as slowly as possible.',
      'Reset and repeat each rep.',
    ],
    commonMistakes: ['Dropping too fast', 'Shrugging at the top'],
    defaultSets: 3,
    defaultReps: '5',
    restSeconds: 75,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    category: 'pull',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['pullUpBar', 'gym'],
    difficulty: 'advanced',
    progressionOf: 'negative-pull-up',
    instructionSteps: [
      'Hang with hands just wider than shoulders.',
      'Pull chest toward the bar, chin over.',
      'Lower with control to a full hang.',
    ],
    commonMistakes: ['Kipping or swinging', 'Cutting the range short'],
    defaultSets: 3,
    defaultReps: '5–8',
    restSeconds: 90,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },

  // ---- Mobility / warm-up pool (3) ----
  {
    id: 'leg-swings',
    name: 'Leg Swings',
    category: 'mobility',
    primaryMuscles: ['hips'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Hold support, swing one leg front to back.',
      'Stay tall, let the hip open.',
      'Then swing side to side.',
    ],
    commonMistakes: ['Forcing the range', 'Twisting the torso'],
    defaultSets: 1,
    defaultReps: '10 / direction',
    restSeconds: 0,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    category: 'mobility',
    primaryMuscles: ['hips', 'thoracic'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Step into a deep lunge, hands down.',
      'Rotate the inside arm to the sky.',
      'Return and switch sides.',
    ],
    commonMistakes: ['Back knee collapsing', 'Rushing the rotation'],
    defaultSets: 1,
    defaultReps: '5 / side',
    restSeconds: 0,
    estSecondsPerSet: 60,
    runInterference: 'low',
  },
  {
    id: 'cat-cow',
    name: 'Cat-Cow',
    category: 'mobility',
    primaryMuscles: ['spine'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'On all fours, round the spine up.',
      'Then drop the belly and lift the chest.',
      'Flow with your breath.',
    ],
    commonMistakes: ['Moving only the neck', 'Holding the breath'],
    defaultSets: 1,
    defaultReps: '8 flows',
    restSeconds: 0,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
]

export const EXERCISE_BY_ID: Record<string, StrengthExercise> = Object.fromEntries(
  STRENGTH_LIBRARY.map((e) => [e.id, e]),
)

export function getExercise(id: string): StrengthExercise | undefined {
  return EXERCISE_BY_ID[id]
}
