import type { StrengthExercise } from './types'

// Seed library — 47 strength exercises across legs/core/push/pull, plus a
// mobility pool for warm-up/cool-down. Bodyweight-first: every category is
// performable with equipment: ['none']. Bundled as a constant (not seeded into
// Dexie). estSecondsPerSet includes the working set only; rest is added by the
// duration math in resolve.ts.

export const STRENGTH_LIBRARY: StrengthExercise[] = [
  // ---- Legs (6) ----
  {
    id: 'bw-squat',
    name: 'Bodyweight Squat',
    category: 'legs',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    regressionOf: 'split-squat',
    instructionSteps: [
      'Stand feet shoulder-width, toes slightly out.',
      'Sit hips back and down, chest tall.',
      'Drive through mid-foot to stand.',
    ],
    commonMistakes: ['Knees caving inward', 'Heels lifting off the floor'],
    defaultSets: 3,
    defaultReps: '12–15',
    restSeconds: 45,
    estSecondsPerSet: 40,
    runInterference: 'high',
  },
  {
    id: 'split-squat',
    name: 'Split Squat',
    category: 'legs',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['none', 'dumbbells'],
    difficulty: 'intermediate',
    progressionOf: 'bw-squat',
    regressionOf: 'bulgarian-split-squat',
    instructionSteps: [
      'Stagger stance, one long stride apart.',
      'Lower back knee toward the floor.',
      'Push through front heel to rise.',
    ],
    commonMistakes: ['Front knee drifting past toes', 'Leaning too far forward'],
    defaultSets: 3,
    defaultReps: '10 / leg',
    restSeconds: 60,
    estSecondsPerSet: 50,
    runInterference: 'high',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'legs',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['none', 'dumbbells'],
    difficulty: 'advanced',
    progressionOf: 'split-squat',
    instructionSteps: [
      'Rest rear foot on a chair or bench.',
      'Lower straight down over the front foot.',
      'Keep front shin near vertical.',
    ],
    commonMistakes: ['Bouncing at the bottom', 'Weight shifting onto back foot'],
    defaultSets: 3,
    defaultReps: '8 / leg',
    restSeconds: 60,
    estSecondsPerSet: 55,
    runInterference: 'high',
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'legs',
    primaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['none'],
    difficulty: 'beginner',
    regressionOf: 'single-leg-glute-bridge',
    instructionSteps: [
      'Lie on back, knees bent, feet flat.',
      'Squeeze glutes and lift hips to a line.',
      'Pause at the top, lower with control.',
    ],
    commonMistakes: ['Arching the lower back', 'Pushing through the toes'],
    defaultSets: 3,
    defaultReps: '15',
    restSeconds: 40,
    estSecondsPerSet: 35,
    runInterference: 'medium',
  },
  {
    id: 'single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    category: 'legs',
    primaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['none'],
    difficulty: 'intermediate',
    progressionOf: 'glute-bridge',
    instructionSteps: [
      'Bridge position, extend one leg straight.',
      'Lift hips using the planted leg only.',
      'Keep hips level throughout.',
    ],
    commonMistakes: ['Hips tilting to one side', 'Using momentum to swing up'],
    defaultSets: 3,
    defaultReps: '10 / leg',
    restSeconds: 45,
    estSecondsPerSet: 45,
    runInterference: 'medium',
  },
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    category: 'legs',
    primaryMuscles: ['calves'],
    equipment: ['none', 'dumbbells'],
    difficulty: 'beginner',
    instructionSteps: [
      'Stand tall, balls of feet on an edge.',
      'Rise onto toes as high as possible.',
      'Lower slowly below the step.',
    ],
    commonMistakes: ['Rushing the reps', 'Not using full range of motion'],
    defaultSets: 3,
    defaultReps: '20',
    restSeconds: 40,
    estSecondsPerSet: 35,
    runInterference: 'medium',
  },

  {
    id: 'freehand-jump-squat',
    name: 'Freehand Jump Squat',
    category: 'legs',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['none'],
    difficulty: 'intermediate',
    progressionOf: 'bw-squat',
    instructionSteps: [
      'Squat down until thighs are near parallel.',
      'Drive through the feet and jump straight up.',
      'Land soft and sink into the next rep.',
    ],
    commonMistakes: ['Landing with stiff, straight legs', 'Letting knees cave on landing'],
    defaultSets: 3,
    defaultReps: '8–10',
    restSeconds: 60,
    estSecondsPerSet: 40,
    runInterference: 'high',
  },
  {
    id: 'dumbbell-squat',
    name: 'Dumbbell Squat',
    category: 'legs',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['dumbbells', 'gym'],
    difficulty: 'beginner',
    instructionSteps: [
      'Hold a dumbbell at each side, feet shoulder-width.',
      'Sit hips back and down, chest tall.',
      'Drive through the heels to stand.',
    ],
    commonMistakes: ['Knees drifting past the toes', 'Rounding the lower back'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'high',
  },
  {
    id: 'dumbbell-rear-lunge',
    name: 'Dumbbell Rear Lunge',
    category: 'legs',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['dumbbells', 'gym'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Hold dumbbells at your sides, stand tall.',
      'Step one foot back and lower the knee.',
      'Push through the front heel to return.',
    ],
    commonMistakes: ['Front knee sliding past the toes', 'Torso leaning forward'],
    defaultSets: 3,
    defaultReps: '10 / leg',
    restSeconds: 60,
    estSecondsPerSet: 50,
    runInterference: 'high',
  },
  {
    id: 'glute-kickback',
    name: 'Glute Kickback',
    category: 'legs',
    primaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'On all fours, knee bent at 90 degrees.',
      'Press the sole up until the thigh is level.',
      'Squeeze the glute, lower with control.',
    ],
    commonMistakes: ['Arching the lower back to lift', 'Swinging the leg with momentum'],
    defaultSets: 3,
    defaultReps: '12 / leg',
    restSeconds: 40,
    estSecondsPerSet: 40,
    runInterference: 'medium',
  },
  {
    id: 'stiff-legged-deadlift',
    name: 'Stiff-Legged Dumbbell Deadlift',
    category: 'legs',
    primaryMuscles: ['hamstrings', 'glutes'],
    equipment: ['dumbbells', 'gym'],
    difficulty: 'beginner',
    instructionSteps: [
      'Hold dumbbells in front, knees softly bent.',
      'Hinge at the hips, back flat, lowering the weights.',
      'Feel the hamstrings stretch, then stand tall.',
    ],
    commonMistakes: ['Rounding the back', 'Bending the knees too much'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'high',
  },
  {
    id: 'step-up-knee-raise',
    name: 'Step-Up with Knee Raise',
    category: 'legs',
    primaryMuscles: ['glutes', 'quads'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Face a sturdy box or bench, feet together.',
      'Step up and drive the other knee high.',
      'Step down with control and switch legs.',
    ],
    commonMistakes: ['Pushing off the back foot', 'Letting the standing knee cave in'],
    defaultSets: 3,
    defaultReps: '8 / leg',
    restSeconds: 45,
    estSecondsPerSet: 45,
    runInterference: 'high',
  },

  // ---- Core (6) ----
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    category: 'core',
    primaryMuscles: ['deep core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Lie on back, arms up, knees over hips.',
      'Lower opposite arm and leg slowly.',
      'Keep lower back pressed to the floor.',
    ],
    commonMistakes: ['Back arching off the floor', 'Holding your breath'],
    defaultSets: 3,
    defaultReps: '10 / side',
    restSeconds: 30,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    primaryMuscles: ['core', 'shoulders'],
    equipment: ['none'],
    difficulty: 'beginner',
    regressionOf: 'side-plank',
    instructionSteps: [
      'Forearms under shoulders, body in a line.',
      'Brace abs and squeeze glutes.',
      'Hold steady, breathe normally.',
    ],
    commonMistakes: ['Hips sagging or piking up', 'Dropping the head'],
    defaultSets: 3,
    defaultReps: '45s hold',
    restSeconds: 40,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'core',
    primaryMuscles: ['obliques'],
    equipment: ['none'],
    difficulty: 'intermediate',
    progressionOf: 'plank',
    instructionSteps: [
      'Forearm under shoulder, stack the feet.',
      'Lift hips into a straight side line.',
      'Hold tall, then switch sides.',
    ],
    commonMistakes: ['Hips sinking toward the floor', 'Rotating the chest down'],
    defaultSets: 2,
    defaultReps: '30s / side',
    restSeconds: 40,
    estSecondsPerSet: 60,
    runInterference: 'low',
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    category: 'core',
    primaryMuscles: ['core', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'On all fours, wrists under shoulders.',
      'Extend opposite arm and leg level.',
      'Pause, return, keep hips square.',
    ],
    commonMistakes: ['Twisting the torso', 'Overarching the lower back'],
    defaultSets: 3,
    defaultReps: '10 / side',
    restSeconds: 30,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Hold',
    category: 'core',
    primaryMuscles: ['core'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Lie on back, arms overhead, legs straight.',
      'Lift shoulders and legs off the floor.',
      'Press lower back down, hold the dish.',
    ],
    commonMistakes: ['Lower back lifting off the floor', 'Raising legs too high'],
    defaultSets: 3,
    defaultReps: '30s hold',
    restSeconds: 40,
    estSecondsPerSet: 35,
    runInterference: 'low',
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    category: 'core',
    primaryMuscles: ['core', 'hip flexors'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Start in a strong push-up position.',
      'Drive knees toward chest, alternating fast.',
      'Keep hips low and shoulders stacked.',
    ],
    commonMistakes: ['Hips bouncing high', 'Hands drifting forward'],
    defaultSets: 3,
    defaultReps: '30s',
    restSeconds: 30,
    estSecondsPerSet: 35,
    runInterference: 'medium',
  },

  {
    id: 'sit-up',
    name: 'Sit-Up',
    category: 'core',
    primaryMuscles: ['core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Lie on your back, knees bent, feet planted.',
      'Curl all the way up toward the thighs.',
      'Lower with control, keep tension on the abs.',
    ],
    commonMistakes: ['Yanking on the neck', 'Using momentum to swing up'],
    defaultSets: 3,
    defaultReps: '15–20',
    restSeconds: 30,
    estSecondsPerSet: 35,
    runInterference: 'low',
  },
  {
    id: 'air-bike',
    name: 'Air Bike',
    category: 'core',
    primaryMuscles: ['core', 'obliques'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Lie back, hands by your head, knees up.',
      'Bring elbow to the opposite knee, cycling.',
      'Keep the lower back pressed to the floor.',
    ],
    commonMistakes: ['Pulling on the neck', 'Feet dropping toward the floor'],
    defaultSets: 3,
    defaultReps: '15 / side',
    restSeconds: 30,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: 'core',
    primaryMuscles: ['obliques'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Sit leaning back, knees bent, heels light.',
      'Clasp the hands and rotate side to side.',
      'Move from the waist, not just the arms.',
    ],
    commonMistakes: ['Rounding the lower back', 'Twisting only the shoulders'],
    defaultSets: 3,
    defaultReps: '15 / side',
    restSeconds: 30,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'reverse-crunch',
    name: 'Reverse Crunch',
    category: 'core',
    primaryMuscles: ['core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Lie back, thighs vertical, palms down.',
      'Curl the hips up, knees toward the chest.',
      'Lower slowly without dropping the legs.',
    ],
    commonMistakes: ['Swinging the legs for momentum', 'Arching the back off the floor'],
    defaultSets: 3,
    defaultReps: '15',
    restSeconds: 30,
    estSecondsPerSet: 35,
    runInterference: 'low',
  },
  {
    id: 'lying-leg-raise',
    name: 'Lying Leg Raise',
    category: 'core',
    primaryMuscles: ['core', 'hip flexors'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Lie flat, hands under the glutes, legs straight.',
      'Raise the legs to vertical, knees soft.',
      'Lower slowly, stopping before the floor.',
    ],
    commonMistakes: ['Lower back lifting off the floor', 'Dropping the legs down fast'],
    defaultSets: 3,
    defaultReps: '12–15',
    restSeconds: 30,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'hyperextension',
    name: 'Hyperextension',
    category: 'core',
    primaryMuscles: ['lower back', 'glutes'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Hips at a bench edge, ankles anchored.',
      'Hinge down with a flat back, arms crossed.',
      'Raise to a straight line — do not overarch.',
    ],
    commonMistakes: ['Arching past a straight line', 'Swinging the torso up'],
    defaultSets: 3,
    defaultReps: '12–15',
    restSeconds: 40,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },

  // ---- Push (5) ----
  {
    id: 'incline-push-up',
    name: 'Incline / Knee Push-Up',
    category: 'push',
    primaryMuscles: ['chest', 'triceps'],
    equipment: ['none'],
    difficulty: 'beginner',
    regressionOf: 'push-up',
    instructionSteps: [
      'Hands on a raised surface or knees down.',
      'Lower chest with elbows about 45°.',
      'Press back up, body in a line.',
    ],
    commonMistakes: ['Flaring elbows wide', 'Hips leading the movement'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 45,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'push',
    primaryMuscles: ['chest', 'triceps', 'shoulders'],
    equipment: ['none'],
    difficulty: 'intermediate',
    progressionOf: 'incline-push-up',
    regressionOf: 'diamond-push-up',
    instructionSteps: [
      'Hands under shoulders, body braced straight.',
      'Lower until chest nearly touches floor.',
      'Press up fully, elbows tucked ~45°.',
    ],
    commonMistakes: ['Sagging hips', 'Partial range of motion'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 60,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'diamond-push-up',
    name: 'Diamond Push-Up',
    category: 'push',
    primaryMuscles: ['triceps', 'chest'],
    equipment: ['none'],
    difficulty: 'advanced',
    progressionOf: 'push-up',
    instructionSteps: [
      'Form a diamond with your hands.',
      'Lower chest toward the hands.',
      'Keep elbows tight to the body.',
    ],
    commonMistakes: ['Elbows flaring outward', 'Hips rising first'],
    defaultSets: 3,
    defaultReps: '8–10',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-Up',
    category: 'push',
    primaryMuscles: ['shoulders', 'triceps'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Hips high in an inverted-V shape.',
      'Lower the crown of your head down.',
      'Press back up over the hands.',
    ],
    commonMistakes: ['Letting hips drop mid-rep', 'Hands too far forward'],
    defaultSets: 3,
    defaultReps: '8–10',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'push',
    primaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbells', 'gym'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Dumbbells at shoulders, elbows under wrists.',
      'Brace core, press straight overhead.',
      'Lower under control to the shoulders.',
    ],
    commonMistakes: ['Arching the lower back', 'Pressing the weights forward'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },

  {
    id: 'handstand-push-up',
    name: 'Handstand Push-Up',
    category: 'push',
    primaryMuscles: ['shoulders', 'triceps'],
    equipment: ['none'],
    difficulty: 'advanced',
    progressionOf: 'pike-push-up',
    instructionSteps: [
      'Kick up to a handstand against a wall.',
      'Lower until the head nearly touches the floor.',
      'Press back up to full arm extension.',
    ],
    commonMistakes: ['Arching the back off the wall', 'Dropping down too fast'],
    defaultSets: 3,
    defaultReps: '5–8',
    restSeconds: 90,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'bench-dip',
    name: 'Bench Dip',
    category: 'push',
    primaryMuscles: ['triceps', 'chest'],
    equipment: ['none'],
    difficulty: 'beginner',
    regressionOf: 'triceps-dip',
    instructionSteps: [
      'Hands on a bench edge, legs out front.',
      'Bend the elbows to lower the hips down.',
      'Press back up, keeping elbows tucked back.',
    ],
    commonMistakes: ['Elbows flaring out wide', 'Shrugging the shoulders up'],
    defaultSets: 3,
    defaultReps: '12–15',
    restSeconds: 45,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'triceps-dip',
    name: 'Parallel Bar Dip',
    category: 'push',
    primaryMuscles: ['triceps', 'chest'],
    equipment: ['pullUpBar', 'gym'],
    difficulty: 'intermediate',
    progressionOf: 'bench-dip',
    instructionSteps: [
      'Support yourself on bars, arms locked.',
      'Lower until elbows reach about 90 degrees.',
      'Press up, torso upright, elbows close.',
    ],
    commonMistakes: ['Dropping too deep on the shoulders', 'Swinging the legs for momentum'],
    defaultSets: 3,
    defaultReps: '8–10',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'push-up-to-side-plank',
    name: 'Push-Up to Side Plank',
    category: 'push',
    primaryMuscles: ['chest', 'core', 'shoulders'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructionSteps: [
      'Do one push-up in a strong plank.',
      'As you rise, rotate into a side plank.',
      'Reach the top arm up, then alternate sides.',
    ],
    commonMistakes: ['Hips sagging during the push-up', 'Rushing the rotation'],
    defaultSets: 3,
    defaultReps: '8 / side',
    restSeconds: 60,
    estSecondsPerSet: 50,
    runInterference: 'low',
  },
  {
    id: 'plyo-push-up',
    name: 'Plyo Push-Up',
    category: 'push',
    primaryMuscles: ['chest', 'triceps', 'shoulders'],
    equipment: ['none'],
    difficulty: 'advanced',
    progressionOf: 'push-up',
    instructionSteps: [
      'Lower into a push-up, body braced straight.',
      'Push up explosively so the hands leave the floor.',
      'Land soft and sink into the next rep.',
    ],
    commonMistakes: ['Sagging hips on landing', 'Cutting the depth short'],
    defaultSets: 3,
    defaultReps: '6–8',
    restSeconds: 75,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'dumbbell-flyes',
    name: 'Dumbbell Flyes',
    category: 'push',
    primaryMuscles: ['chest'],
    equipment: ['dumbbells', 'gym'],
    difficulty: 'beginner',
    instructionSteps: [
      'Lie on a bench, dumbbells pressed above the chest.',
      'Open the arms wide in an arc, elbows soft.',
      'Squeeze the chest to bring them back together.',
    ],
    commonMistakes: ['Bending the elbows like a press', 'Lowering the weights too far'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },

  // ---- Pull (4) ----
  {
    id: 'band-row',
    name: 'Band / Towel Row',
    category: 'pull',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['none', 'resistanceBand'],
    difficulty: 'beginner',
    regressionOf: 'dumbbell-row',
    instructionSteps: [
      'Anchor a band (or towel around a post).',
      'Row elbows back, squeezing shoulder blades.',
      'Return slowly, keeping chest tall.',
    ],
    commonMistakes: ['Shrugging the shoulders', 'Using momentum to yank'],
    defaultSets: 3,
    defaultReps: '12–15',
    restSeconds: 45,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    category: 'pull',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['dumbbells', 'gym'],
    difficulty: 'intermediate',
    progressionOf: 'band-row',
    instructionSteps: [
      'Hinge at hips, flat back, one hand supported.',
      'Row the dumbbell to your hip.',
      'Lower fully, feeling the lat stretch.',
    ],
    commonMistakes: ['Rounding the back', 'Twisting the torso to lift'],
    defaultSets: 3,
    defaultReps: '10 / side',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'negative-pull-up',
    name: 'Negative Pull-Up',
    category: 'pull',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['pullUpBar', 'gym'],
    difficulty: 'intermediate',
    regressionOf: 'pull-up',
    instructionSteps: [
      'Jump or step to the top position.',
      'Lower yourself as slowly as possible.',
      'Reset and repeat each rep.',
    ],
    commonMistakes: ['Dropping too fast', 'Shrugging at the top'],
    defaultSets: 3,
    defaultReps: '5',
    restSeconds: 75,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    category: 'pull',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['pullUpBar', 'gym'],
    difficulty: 'advanced',
    progressionOf: 'negative-pull-up',
    instructionSteps: [
      'Hang with hands just wider than shoulders.',
      'Pull chest toward the bar, chin over.',
      'Lower with control to a full hang.',
    ],
    commonMistakes: ['Kipping or swinging', 'Cutting the range short'],
    defaultSets: 3,
    defaultReps: '5–8',
    restSeconds: 90,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },

  {
    id: 'scapular-pull-up',
    name: 'Scapular Pull-Up',
    category: 'pull',
    primaryMuscles: ['traps', 'back'],
    equipment: ['pullUpBar', 'gym'],
    difficulty: 'beginner',
    regressionOf: 'negative-pull-up',
    instructionSteps: [
      'Hang from the bar with straight arms.',
      'Without bending the elbows, pull the shoulders down.',
      'Pause, then rise back to a full hang.',
    ],
    commonMistakes: ['Bending the elbows to cheat', 'Rushing through the reps'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 45,
    estSecondsPerSet: 35,
    runInterference: 'low',
  },
  {
    id: 'chin-up',
    name: 'Chin-Up',
    category: 'pull',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['pullUpBar', 'gym'],
    difficulty: 'intermediate',
    regressionOf: 'pull-up',
    instructionSteps: [
      'Hang with palms facing you, hands close.',
      'Pull the chest up until the chin clears the bar.',
      'Lower with control to a full hang.',
    ],
    commonMistakes: ['Kipping or swinging', 'Cutting the range short'],
    defaultSets: 3,
    defaultReps: '5–8',
    restSeconds: 90,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'inverted-row',
    name: 'Inverted Row',
    category: 'pull',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['gym'],
    difficulty: 'intermediate',
    progressionOf: 'band-row',
    instructionSteps: [
      'Hang under a waist-high bar, body straight.',
      'Pull the chest to the bar, squeezing the blades.',
      'Lower slowly to full arm extension.',
    ],
    commonMistakes: ['Hips sagging toward the floor', 'Shrugging the shoulders up'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 60,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'dumbbell-bicep-curl',
    name: 'Dumbbell Bicep Curl',
    category: 'pull',
    primaryMuscles: ['biceps'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructionSteps: [
      'Stand tall, a dumbbell in each hand.',
      'Curl the weights up, elbows pinned to the sides.',
      'Lower slowly under control.',
    ],
    commonMistakes: ['Swinging the torso to lift', 'Elbows drifting forward'],
    defaultSets: 3,
    defaultReps: '10–12',
    restSeconds: 45,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'dumbbell-shrug',
    name: 'Dumbbell Shrug',
    category: 'pull',
    primaryMuscles: ['traps'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructionSteps: [
      'Stand with a dumbbell in each hand, arms long.',
      'Lift the shoulders straight up toward the ears.',
      'Hold the squeeze, then lower fully.',
    ],
    commonMistakes: ['Rolling the shoulders', 'Bending the elbows to help'],
    defaultSets: 3,
    defaultReps: '12–15',
    restSeconds: 40,
    estSecondsPerSet: 35,
    runInterference: 'low',
  },

  // ---- Mobility / warm-up pool (13) ----
  {
    id: 'leg-swings',
    name: 'Leg Swings',
    category: 'mobility',
    primaryMuscles: ['hips'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Hold support, swing one leg front to back.',
      'Stay tall, let the hip open.',
      'Then swing side to side.',
    ],
    commonMistakes: ['Forcing the range', 'Twisting the torso'],
    defaultSets: 1,
    defaultReps: '10 / direction',
    restSeconds: 0,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    category: 'mobility',
    primaryMuscles: ['hips', 'thoracic'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Step into a deep lunge, hands down.',
      'Rotate the inside arm to the sky.',
      'Return and switch sides.',
    ],
    commonMistakes: ['Back knee collapsing', 'Rushing the rotation'],
    defaultSets: 1,
    defaultReps: '5 / side',
    restSeconds: 0,
    estSecondsPerSet: 60,
    runInterference: 'low',
  },
  {
    id: 'cat-cow',
    name: 'Cat-Cow',
    category: 'mobility',
    primaryMuscles: ['spine'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'On all fours, round the spine up.',
      'Then drop the belly and lift the chest.',
      'Flow with your breath.',
    ],
    commonMistakes: ['Moving only the neck', 'Holding the breath'],
    defaultSets: 1,
    defaultReps: '8 flows',
    restSeconds: 0,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },

  // Dynamic — run warm-up pool
  {
    id: 'hip-circles',
    name: 'Hip Circles',
    category: 'mobility',
    primaryMuscles: ['hips'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Stand tall, lift one knee to hip height.',
      'Draw a wide circle with the knee.',
      'Reverse the direction, then switch legs.',
    ],
    commonMistakes: ['Leaning the torso away', 'Rushing through small circles'],
    defaultSets: 1,
    defaultReps: '8 / direction',
    restSeconds: 0,
    estSecondsPerSet: 40,
    runInterference: 'low',
  },
  {
    id: 'walking-lunge',
    name: 'Walking Lunge',
    category: 'mobility',
    primaryMuscles: ['quads', 'glutes', 'hips'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Step forward into a long stride.',
      'Lower the back knee toward the floor.',
      'Drive up and step through to the other side.',
    ],
    commonMistakes: ['Short, choppy steps', 'Front knee caving inward'],
    defaultSets: 1,
    defaultReps: '5 / leg',
    restSeconds: 0,
    estSecondsPerSet: 45,
    runInterference: 'low',
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    category: 'mobility',
    primaryMuscles: ['hip flexors', 'calves'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Jog in place, driving knees to hip height.',
      'Stay on the balls of your feet.',
      'Pump the arms in rhythm.',
    ],
    commonMistakes: ['Leaning back', 'Letting the knees stay low'],
    defaultSets: 1,
    defaultReps: '20s',
    restSeconds: 0,
    estSecondsPerSet: 20,
    runInterference: 'low',
  },
  {
    id: 'butt-kicks',
    name: 'Butt Kicks',
    category: 'mobility',
    primaryMuscles: ['hamstrings', 'quads'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Jog in place, heels flicking to the glutes.',
      'Keep knees pointing down, hips tall.',
      'Stay light and quick on the feet.',
    ],
    commonMistakes: ['Bending forward at the waist', 'Kicking with the knees forward'],
    defaultSets: 1,
    defaultReps: '20s',
    restSeconds: 0,
    estSecondsPerSet: 20,
    runInterference: 'low',
  },
  {
    id: 'ankle-hops',
    name: 'Ankle Hops',
    category: 'mobility',
    primaryMuscles: ['calves', 'ankles'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Small quick hops off the balls of your feet.',
      'Keep the knees almost straight.',
      'Land softly and spring straight back up.',
    ],
    commonMistakes: ['Bending the knees to jump', 'Landing heavy on the heels'],
    defaultSets: 1,
    defaultReps: '15s',
    restSeconds: 0,
    estSecondsPerSet: 15,
    runInterference: 'low',
  },

  // Static — run cool-down pool
  {
    id: 'calf-stretch',
    name: 'Calf Stretch',
    category: 'mobility',
    primaryMuscles: ['calves'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Hands on a wall, step one foot far back.',
      'Press the back heel into the floor.',
      'Keep the back leg straight and hold.',
    ],
    commonMistakes: ['Letting the back heel lift', 'Bouncing in the stretch'],
    defaultSets: 1,
    defaultReps: '30s / side',
    restSeconds: 0,
    estSecondsPerSet: 60,
    runInterference: 'low',
  },
  {
    id: 'quad-stretch',
    name: 'Standing Quad Stretch',
    category: 'mobility',
    primaryMuscles: ['quads', 'hip flexors'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Stand tall, pull one heel toward the glute.',
      'Keep knees together and hips pushed forward.',
      'Hold, then switch legs.',
    ],
    commonMistakes: ['Arching the lower back', 'Letting the knee flare out'],
    defaultSets: 1,
    defaultReps: '30s / side',
    restSeconds: 0,
    estSecondsPerSet: 60,
    runInterference: 'low',
  },
  {
    id: 'hamstring-stretch',
    name: 'Hamstring Stretch',
    category: 'mobility',
    primaryMuscles: ['hamstrings'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Step one heel forward, toes up.',
      'Hinge at the hips with a flat back.',
      'Feel the stretch behind the thigh and hold.',
    ],
    commonMistakes: ['Rounding the lower back', 'Locking the knee hard'],
    defaultSets: 1,
    defaultReps: '30s / side',
    restSeconds: 0,
    estSecondsPerSet: 60,
    runInterference: 'low',
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Kneeling Hip Flexor Stretch',
    category: 'mobility',
    primaryMuscles: ['hip flexors'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Kneel on one knee, other foot forward.',
      'Tuck the pelvis and shift gently forward.',
      'Stay tall through the chest and hold.',
    ],
    commonMistakes: ['Arching the lower back', 'Front knee drifting past the toes'],
    defaultSets: 1,
    defaultReps: '30s / side',
    restSeconds: 0,
    estSecondsPerSet: 60,
    runInterference: 'low',
  },
  {
    id: 'figure-4-stretch',
    name: 'Figure-4 Glute Stretch',
    category: 'mobility',
    primaryMuscles: ['glutes', 'hips'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructionSteps: [
      'Lie on your back, knees bent.',
      'Cross one ankle over the opposite knee.',
      'Pull the back thigh toward you and hold.',
    ],
    commonMistakes: ['Lifting the head and shoulders', 'Pulling into sharp pain'],
    defaultSets: 1,
    defaultReps: '30s / side',
    restSeconds: 0,
    estSecondsPerSet: 60,
    runInterference: 'low',
  },
]

export const EXERCISE_BY_ID: Record<string, StrengthExercise> = Object.fromEntries(
  STRENGTH_LIBRARY.map((e) => [e.id, e]),
)

export function getExercise(id: string): StrengthExercise | undefined {
  return EXERCISE_BY_ID[id]
}
