import { ScreenHeader, Card, SectionTitle } from '@/components/ui'
import { useActivePlan, useActiveGoal, useLatestAssessment } from '@/app/hooks'
import { useUnits } from '@/app/hooks'
import { formatPaceRange } from '@/lib/formatters'

// Coach tab is a stub this build (spec Phase 6 adds chat/recap/adaptation). We
// surface the derived training paces here so the tab is useful, not empty.
export function CoachScreen() {
  const plan = useActivePlan()
  const goal = useActiveGoal()
  const assessment = useLatestAssessment()
  const units = useUnits()
  const zones = assessment?.derivedPaceZones

  return (
    <div>
      <ScreenHeader title="Coach" subtitle="Offline mode" />

      <div className="px-4">
        <Card>
          <p className="text-slate-200 font-medium">Your AI coach is coming</p>
          <p className="text-sm text-slate-400 mt-1">
            Chat, weekly recaps, and automatic plan adaptation land in a later build. For now, your plan is generated by the rule-based engine using proven training logic.
          </p>
        </Card>

        {goal && plan && (
          <>
            <SectionTitle>Current plan</SectionTitle>
            <Card>
              <p className="text-slate-100 font-medium capitalize">
                {goal.type} · {plan.weeks} weeks · {plan.engine === 'template' ? 'template' : 'adaptive (rule)'}
              </p>
              <p className="text-sm text-slate-500 mt-0.5">
                {plan.startDate} → {plan.endDate}
              </p>
            </Card>
          </>
        )}

        {zones && (
          <>
            <SectionTitle>Your training paces</SectionTitle>
            <Card className="flex flex-col gap-2">
              <PaceRow label="Easy" range={formatPaceRange(zones.easy, units)} />
              <PaceRow label="Marathon" range={formatPaceRange(zones.marathon, units)} />
              <PaceRow label="Threshold" range={formatPaceRange(zones.threshold, units)} />
              <PaceRow label="Interval" range={formatPaceRange(zones.interval, units)} />
              <PaceRow label="Repetition" range={formatPaceRange(zones.repetition, units)} />
              {assessment?.derivedVdot && (
                <p className="text-xs text-slate-500 mt-1">VDOT {assessment.derivedVdot} · reference targets only</p>
              )}
            </Card>
          </>
        )}
      </div>
    </div>
  )
}

function PaceRow({ label, range }: { label: string; range: string }) {
  return (
    <div className="flex justify-between text-sm">
      <span className="text-slate-400">{label}</span>
      <span className="stat-number text-slate-100">{range}</span>
    </div>
  )
}
